application: helpdesk-app
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: assets/img/favicon.ico
  upload: assets/img/favicon.ico

- url: /robots.txt
  static_files: assets/robots.txt
  upload: assets/robots.txt

- url: /assets
  static_dir: assets

- url: /task/.*
  script: tasks.app

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
- name: lxml
  version: latest